#!/usr/bin/env python3
"""
migrate_to_digitalocean.py
1. Queries Render for all MCP services
2. Deletes suspended ones from Render
3. Rewrites docker-compose.yml with only the active services
4. Updates keepalive.yml for new DigitalOcean URLs

Usage:
    python3 migrate_to_digitalocean.py [--dry-run]
"""
import re, sys, time, httpx

API_KEY = "rnd_CvrOOy35aCkeOPhro46TiV8kkkhE"
BASE    = "https://api.render.com/v1"
HDR     = {"Authorization": f"Bearer {API_KEY}", "Accept": "application/json",
           "Content-Type": "application/json"}
DRY_RUN = "--dry-run" in sys.argv

# Maps service name → actual build dir (where dir differs from name)
DIR_OVERRIDE = {
    "irctc-mcp":       "irctc",
    "swiggy-mcp":      "swiggy",
    "wolfram-alpha-mcp": "wolfram-alpha",
    "youtube-mcp":     "youtube",
    "zomato-mcp":      "zomato",
}

# All env vars each service needs
ENV_VARS = {
    "home-assistant-mcp":  ["HA_URL", "HA_TOKEN"],
    "spotify-mcp":         ["SPOTIFY_CLIENT_ID", "SPOTIFY_CLIENT_SECRET"],
    "discord-mcp":         ["DISCORD_WEBHOOK_URL"],
    "notion-mcp":          ["NOTION_API_KEY"],
    "google-maps-mcp":     ["GOOGLE_MAPS_API_KEY"],
    "google-sheets-mcp":   ["GOOGLE_SERVICE_ACCOUNT_JSON"],
    "google-translate-mcp":["GOOGLE_TRANSLATE_API_KEY"],
    "google-photos-mcp":   ["GOOGLE_PHOTOS_ACCESS_TOKEN"],
    "strava-mcp":          ["STRAVA_CLIENT_ID", "STRAVA_CLIENT_SECRET", "STRAVA_REFRESH_TOKEN"],
    "gtfs-mcp":            ["GTFS_FEED_URL"],
    "irctc-mcp":           ["RAPIDAPI_KEY"],
    "wolfram-alpha-mcp":   ["WOLFRAM_APP_ID"],
}

def get_mcp_services(client):
    owners = client.get(f"{BASE}/owners?limit=10").json()
    oid = owners[0]["owner"]["id"]
    print(f"Account: {owners[0]['owner']['name']}\n")
    data = client.get(f"{BASE}/services?ownerId={oid}&limit=100").json()
    svcs = []
    for item in data:
        s = item["service"]
        name = s["name"]
        # Normalise names with random 4-char suffixes
        parts = name.rsplit("-", 1)
        canon = parts[0] if len(parts) == 2 and re.match(r'^[a-z0-9]{4}$', parts[1]) else name
        if "mcp" in canon or canon in DIR_OVERRIDE.values():
            svcs.append({
                "id":        s["id"],
                "name":      canon,
                "actual":    name,
                "suspended": s.get("suspended", "not_suspended"),
                "url":       s.get("serviceDetails", {}).get("url", ""),
            })
    return svcs

def delete_service(client, sid, name):
    r = client.delete(f"{BASE}/services/{sid}")
    return r.status_code in (200, 204)

def build_compose(active_services):
    lines = [
        "version: '3.8'\n",
        "# Auto-generated by migrate_to_digitalocean.py — only active services.\n",
        "# Deploy on a DigitalOcean Droplet:  docker compose up -d --build\n\n",
        "services:\n\n",
        "  caddy:\n",
        "    image: caddy:2-alpine\n",
        "    restart: unless-stopped\n",
        "    ports:\n",
        "      - \"80:80\"\n",
        "      - \"443:443\"\n",
        "      - \"443:443/udp\"\n",
        "    volumes:\n",
        "      - ./Caddyfile:/etc/caddy/Caddyfile:ro\n",
        "      - caddy_data:/data\n",
        "      - caddy_config:/config\n",
        "    networks:\n",
        "      - mcp-net\n\n",
    ]
    for svc in active_services:
        name = svc["name"]
        build_dir = DIR_OVERRIDE.get(name, name)
        env_keys  = ENV_VARS.get(name, [])
        lines.append(f"  {name}:\n")
        lines.append(f"    build: ./{build_dir}\n")
        lines.append(f"    restart: unless-stopped\n")
        lines.append(f"    environment:\n")
        lines.append(f"      PORT: \"8000\"\n")
        for k in env_keys:
            lines.append(f'      {k}: "${{{k}:-}}"\n')
        lines.append(f"    networks:\n")
        lines.append(f"      - mcp-net\n\n")

    lines += [
        "networks:\n",
        "  mcp-net:\n",
        "    driver: bridge\n\n",
        "volumes:\n",
        "  caddy_data:\n",
        "  caddy_config:\n",
    ]
    return "".join(lines)

def build_caddyfile(active_services):
    header = (
        "{\n"
        "    email {$ADMIN_EMAIL:admin@example.com}\n"
        "}\n\n"
    )
    blocks = []
    for svc in active_services:
        name = svc["name"]
        blocks.append(f"{name}.{{$DOMAIN}} {{\n    reverse_proxy {name}:8000\n}}\n")
    return header + "\n".join(blocks) + "\n"

def build_keepalive(active_services, domain_placeholder="YOUR_DOMAIN"):
    url_lines = "\n".join(
        f'            "https://{s["name"]}.{domain_placeholder}/health"'
        for s in active_services
    )
    return f'''name: Keep Render Services Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping all MCP health endpoints
        run: |
          URLS=(
{url_lines}
          )
          for url in "${{URLS[@]}}"; do
            code=$(curl -s -o /dev/null -w "%{{http_code}}" --max-time 30 "$url" || echo "ERR")
            echo "$code  $url"
          done
'''

def main():
    with httpx.Client(headers=HDR, timeout=30) as client:
        services = get_mcp_services(client)

    active    = [s for s in services if s["suspended"] == "not_suspended"]
    suspended = [s for s in services if s["suspended"] != "not_suspended"]

    print(f"Active ({len(active)}):")
    for s in active:
        print(f"  + {s['name']}  ({s['url'] or 'no url'})")

    print(f"\nSuspended ({len(suspended)}) — will DELETE from Render:")
    for s in suspended:
        print(f"  - {s['name']}")

    if DRY_RUN:
        print("\n[DRY RUN] No changes made.")
        return

    print("\nDeleting suspended services from Render...")
    with httpx.Client(headers=HDR, timeout=30) as client:
        for s in suspended:
            ok = delete_service(client, s["id"], s["name"])
            print(f"  {'DELETED' if ok else 'FAILED ':7s} {s['name']}")
            time.sleep(0.3)

    # Write new docker-compose.yml
    compose = build_compose(active)
    with open("docker-compose.yml", "w") as f:
        f.write(compose)
    print(f"\nWrote docker-compose.yml with {len(active)} services.")

    # Write new Caddyfile
    caddy = build_caddyfile(active)
    with open("Caddyfile", "w") as f:
        f.write(caddy)
    print(f"Wrote Caddyfile with {len(active)} virtual hosts.")

    # Write new keepalive.yml
    keepalive = build_keepalive(active)
    with open(".github/workflows/keepalive.yml", "w") as f:
        f.write(keepalive)
    print("Wrote keepalive.yml (replace YOUR_DOMAIN with your actual domain).")

    print("\nNext steps:")
    print("  1. git add docker-compose.yml Caddyfile .github/workflows/keepalive.yml")
    print("  2. git commit -m 'Trim to active MCPs for DigitalOcean'")
    print("  3. git push origin claude/add-mcp-servers-render-JBTLW")
    print("  4. On your Droplet: git pull && docker compose up -d --build")

if __name__ == "__main__":
    main()
